### ISSUE TITLE
About data curation

### ISSUE THREAD

**Issue by ValkyriaLenneth** [Kiteretsu77/APISR#18]
Dear author:

Please tell me the correct way to set prepare_dataset.sh.

Here I set `data/processed` which contains the I-frames from the previous step.
However, I got:
```
scripts/prepare_datasets.sh: line 4: ./data/processed/: Is a directory
```

Moreover, could you tell me the torch vision version you used?
since the following message shows it has version conflict. 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.3.0+cu121 requires torch==2.3.0, but you have torch 2.3.1 which is incompatible.
Successfully installed torch-2.3.1 torchvision-0.18.1 triton-2.3.1
```
and 
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/GitClone/APISR/scripts/crop_images.py", line 16, in <module>
    from degradation.ESR.usm_sharp import USMSharp
  File "/content/drive/MyDrive/GitClone/APISR/degradation/ESR/usm_sharp.py", line 11, in <module>
    from degradation.ESR.utils import filter2D, np2tensor, tensor2np
  File "/content/drive/MyDrive/GitClone/APISR/degradation/ESR/utils.py", line 18, in <module>
    from degradation.ESR.degradations_functionality import *
  File "/content/drive/MyDrive/GitClone/APISR/degradation/ESR/degradations_functionality.py", line 10, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
Traceback (most recent call last):
  File "/content/drive/MyDrive/GitClone/APISR/scripts/crop_images.py", line 16, in <module>
    from degradation.ESR.usm_sharp import USMSharp
  File "/content/drive/MyDrive/GitClone/APISR/degradation/ESR/usm_sharp.py", line 11, in <module>
    from degradation.ESR.utils import filter2D, np2tensor, tensor2np
  File "/content/drive/MyDrive/GitClone/APISR/degradation/ESR/utils.py", line 18, in <module>
    from degradation.ESR.degradations_functionality import *
  File "/content/drive/MyDrive/GitClone/APISR/degradation/ESR/degradations_functionality.py", line 10, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
```

**Comment by Kiteretsu77** [comment]
The torchvision version should be shown in the install seciont of the README.md.
For the curation bug, please provide more information like how you mangage the input folder and what kinds of variables you change in the _prepare_datasets.sh_. Thanks!

**Comment by ValkyriaLenneth** [comment]
> The torchvision version should be shown in the install seciont of the README.md. For the curation bug, please provide more information like how you mangage the input folder and what kinds of variables you change in the _prepare_datasets.sh_. Thanks!

Really appreciate for your reply and sorry for my negligence for not reading the installation section of README but only install requirement.txt. 

About the folder tree:

APISR
|
|-data # the folder I created for all data
| | -videos # the original animate videos 
| | -processed # the folder of processed I-Frame images
| | -APISR_720p_4xcrop # the folder created by script?

the configuration I overwrote:
```
# Set up the PATH TO THE SOURCE
input_source= "./data/processed/"

# The following three paths will be used widely in opt.py setting!!!
uncropped_hr=data/APISR_720p_4xcrop
degrade_hr_dataset_path=data/train_hr
train_hr_dataset_path=data/train_hr_enhanced
```

Best regard and thank you again

**Comment by Kiteretsu77** [comment]
Sorry for the late reply. I still don't have too much ideas why this bug. I have tried similar naming but it works on my site. I would recommend change the input_source to be another folder that is not "data". And then, make sure that all files in input_source directory is video with "mp4"-style media format. Thanks!
