### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Akamon213** [Kiteretsu77/APISR#21]
请问，本人在预览界面中觉得dat的模型效果更好，但是本人相关知识与水平有限，本地使用时会有报错：
```
D:\Anaconda\envs\apisr\lib\site-packages\timm\models\layers\__init__.py:49: DeprecationWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", DeprecationWarning)
Traceback (most recent call last):
  File "D:\Project\Local\APISR-0.3.0\test_code\inference.py", line 117, in <module>
    generator = load_grl(weight_path, scale=scale)  # GRL for Real-World SR only support 4x upscaling
  File "D:\Project\Local\APISR-0.3.0\test_code\test_utils.py", line 163, in load_grl
    generator.load_state_dict(weight)
  File "D:\Anaconda\envs\apisr\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GRL:
```

简单看代码似乎只能使用GRL和RRDB的模型?应该是需要有改动，还请帮忙解答，谢谢

**Comment by Kiteretsu77** [comment]
在opt.py中你有调整opt['architecture']这个参数吗? 我之前从另外的branch merge DAT. DAT的训练是支持的
